version: 2
updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: increase
    target-branch: "develop"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 3
    labels:
      - "ci"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    target-branch: "develop"
