name: Tests

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]
        types: [opened, synchronize, reopened]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.2, 8.3]
                laravel: [10.*, 11.*, 12.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    - laravel: 10.*
                      testbench: 8.*
                    - laravel: 11.*
                      testbench: 9.*
                    - laravel: 12.*
                      testbench: 10.*
                exclude:
                    - laravel: 12.*
                      php: 8.2

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  COMPOSER_MEMORY_LIMIT=-1 composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --with="laravel/framework:${{ matrix.laravel }}" --with="orchestra/testbench:${{ matrix.testbench }}"

            - name: List Installed Dependencies
              run: composer show -D

            - name: Execute tests
              run: php -d memory_limit=512M vendor/bin/phpunit

            - name: Check code style
              run: vendor/bin/phpcs -p --standard=PSR2 --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 src tests
